---
# See https://github.com/jvautier/project-cli
fullname: jvautier/packer-ubuntu
description: Packer templates for ubuntu.
tags:
  - packer
  - ubuntu
  - ubuntu-desktop
github:
  has_issues: true
  has_projects: false
  has_wiki: false
